#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Need pointing number (1 - 6)"
    exit
fi

FMIN="3850."
FMAX="6650."
LMIN="5450."
LMAX="5550."
EMMW="1000."
B=0
S=0
MASKBALM=""
PYBALM=""
FV=1
VELSTART=""
BALMSUB=""
PINFO=""
PYPLOT="~/snakes/plot_bc_vardisp.py"
MODNAM="/d/monk/eigenbrot/WIYN/14B-0456/anal/models/allZ2_vardisp/allz2_vardisp_batch_interp.fits"

while [[ $# -gt 1 ]]
do
    key=$1
    case $key in
	-b)
	    echo "Setting B"
	    B=1
	    ;;
	-s)
	    S=$2
	    echo "Setting S=$S"
	    shift
	    ;;
	-v)
	    VELSTART=" velstart=$2.,"
	    FV=0
	    echo "Setting V=${V} and allowing velocity to be free"
	    shift
	    ;;
	-e)
	    EMMW=$2
	    echo "Setting emmaskw=${EMMW}"
	    shift
	    ;;
	-f)
	    FMIN=$2
	    FMAX=$3
	    echo "Setting F=[${FMIN}, ${FMAX}]"
	    shift
	    shift
	    ;;
	-l)
	    LMIN=$2
	    LMAX=$3
	    echo "Setting L=[${LMIN}, ${LMAX}]"
	    shift
	    shift
	    ;;
	-d)
	    echo "Plotting withOUT vardisp"
	    PYPLOT="~/snakes/plot_bc.py"
	    MODNAM="/d/monk/eigenbrot/WIYN/14B-0456/anal/models/allZ2/allz2_test.fits"
	    ;;

	-m)
	    MODNAM=$2
	    echo "Using model ${MODNAM}"
	    shift
	    ;;
	-o)
	    O='o'
	    echo "Using offset data"
	    ;;
	-p)
	    PINFO=" parinfofile='$2',"
	    echo "Using${PINFO}"
	    shift
	    ;;
	-c)
	    ERRC=$2
	    echo "Using error suffix $2"
	    shift
	    ;;
	-H)
	    MASKBALM=" /maskbalm,"
	    PYBALM=" -H"
	    echo "Masking Balmer lines"
	    ;;
	-u)
	    BALMSUB="_balmersub"
	    echo "Using balmer subtracted data"
	    ;;
	*)
	    
	    ;;
    esac
    shift
done

P=$1

if [[ $FV -eq 1 ]]; then
    VELOCITY=" velocity='NGC_891_P${P}_bin30_velocities.dat',"
else
    VELOCITY=""
fi

idlcmd="idl -e \"do_simple_allZ2, 'NGC_891_P${P}_bin30${BALMSUB}.ms${O}.fits','NGC_891_P${P}_bin30.me${O}${ERRC}.fits','NGC_891_P${P}_bin30_allz2.dat',location='NGC_891_P${P}_bin30_locations.dat',${VELOCITY} model='${MODNAM}',${PINFO} emmaskw=${EMMW}, wavemin=3800., wavemax=6800.,${VELSTART} fitregion=[${FMIN}, ${FMAX}],${MASKBALM} lightmin=${LMIN}, lightmax=${LMAX}\""

plotcmd="python ${PYPLOT} NGC_891_P${P}_bin30_allz2.coef.fits NGC_891_P${P}_bin30_allz2.fit.fits NGC_891_P${P}_bin30${BALMSUB}.ms${O}.fits NGC_891_P${P}_bin30.me${O}${ERRC}.fits ${MODNAM} -l NGC_891_P${P}_bin30_locations.dat -n${PYBALM}"

chicmd="python ~/snakes/plot_bc_chi.py NGC_891_P${P}_bin30_allz2.chi.fits NGC_891_P${P}_bin30_allz2.coef.fits NGC_891_P${P}_bin30${BALMSUB}.ms${O}.fits -n"

scrfile="P${P}${BALMSUB}.sh"
echo '#!/bin/bash' > $scrfile
echo $idlcmd >> $scrfile
echo $plotcmd >> $scrfile
echo $chicmd >> $scrfile

if [[ $S -gt 1 ]]; then
    echo $plotcmd "-s $S" >> $scrfile
fi

if [[ $B -eq 1 ]]; then
    echo $plotcmd "-b" >> $scrfile
    echo $chicmd "-b" >> $scrfile
    if [[ $S -gt 1 ]]; then
	echo $plotcmd "-b -s $S" >> $scrfile
    fi
fi

chmod +x $scrfile

exit
