#!/bin/bash

PRE=""

if [ $# -eq 1 ]; then
    PRE=$1
fi

for i in `seq 1 6`; do
    if [ ! -x "P$i.sh" ]; then
	echo "P$i.sh is either non-existent or non-executable"
	continue
    fi
    
    echo "Starting screen ${PRE}_P$i"
    screen -S ${PRE}_P$i -d -m ./P$i.sh

done
exit
